"""
Attack Tree DREAD Calculator App
Main Logic
"""
from __future__ import print_function

import ast
import json
import os
import sys
import webbrowser
from pyvis.network import Network

# App's header - displayed before the rest of the commands.
print("================================\n"
      "Attack Tree DREAD Calculator App\n"
      "================================")
print("You will have to input a JSON file and name the output file,"
      "which will automatically open in your browser.\n")

# Instantiate a Network object (creates a visjs network, i.e. a hierarchical attack tree).
ATTACK_TREE_NET = Network(height="100%", width="50%",
                          bgcolor="#222222", font_color="#333333",
                          layout=True)

# "FILE_LOCATION" asks the user for the file's location and holds its value for the next step.
FILE_LOCATION = raw_input("1. Enter the file's location: ")

"""
This function takes the "FILE_LOCATION" variable and based on it opens the JSON file,
reads it in with the help of json module.
literal_eval method is one of the helper functions that helps traverse an abstract syntax tree.
"""
try:
    with open(FILE_LOCATION, 'r') as at_file:
        ATTACK_TREE = json.load(at_file)
        ATTACK_TREE = ast.literal_eval(json.dumps(ATTACK_TREE))
except EnvironmentError:
    print('File not found.')
    sys.exit()

# Extracts nodes from the ATTACK_TREE dictionary into a separate variable.
NODES = ATTACK_TREE['nodes']

"""
This function adds a node to the "ATTACK_TREE_NET" network,
which was instantiated on top of the file, for each node in the "NODES" list.
It assigns values like id, label and title to each node
based on the "id_number" and "label" variables.
Aside from that, it also assigns the node's shape.
"""
for n in NODES:
    id_number = n["id"]
    label = n["name"]

    ATTACK_TREE_NET.add_node(str(id_number), str(label), shape="box", title=label)

# Extracts edges (lines) from the ATTACK_TREE dictionary into a separate variable.
EDGES = ATTACK_TREE['edges']

"""
This function adds an edge, i.e. a line to the "ATTACK_TREE_NET" network,
which was instantiated on top of the file, for each edge in the "EDGES" list.
It assigns values "from" and "to", meaning from which node to which
is it supposed to draw a line.
"""
for e in EDGES:
    to_id = e['to']
    from_id = e['from']
    ATTACK_TREE_NET.add_edge(str(from_id), str(to_id))

# FILE_NAME asks the user to enter the output file's name, i.e.
# the HTML file that will be generated by this programme.
# It is then later used in the show() function of the pyvis library
FILE_NAME = raw_input("2. Enter the output file's name: ")

# show() function writes a static HTML file and saves it locally.
ATTACK_TREE_NET.show(FILE_NAME + ".html")

# 'URL' variable holds the file path for the HTML file generated in the previous function.
# It utilises the "os" and "sys" modules of python to find the path of the current folder.
URL = os.path.join(sys.path[0], FILE_NAME + ".html")

"""
This function (open()), with the help of the "webbrowser" module, opens the previously generated
HTML file in an internet browser (in a new tab).
"""
webbrowser.open("file://" + URL, new=2)
